# Generated by Django 3.2.23 on 2024-01-08 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
                ('description', models.TextField()),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
                ('barcode_image', models.ImageField(blank=True, null=True, upload_to='barcode_images')),
                ('code', models.CharField(editable=False, max_length=32)),
            ],
            options={
                'verbose_name_plural': 'Coupon',
            },
        ),
    ]
