# Generated by Django 3.2.23 on 2024-01-08 20:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=32, unique=True),
        ),
    ]
