# Generated by Django 3.2.23 on 2024-01-09 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={},
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='barcode_image',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='name',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
