# Generated by Django 3.2.23 on 2024-01-08 20:43

import coupon.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_alter_coupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(default=coupon.models.Coupon._generate_code, editable=False, max_length=32, unique=True),
        ),
    ]
