# Generated by Django 3.2.23 on 2024-01-09 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_auto_20240109_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='header',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='description',
            field=models.TextField(default='', max_length=255),
        ),
    ]
