# Generated by Django 3.2.23 on 2024-01-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='date',
        ),
        migrations.AddField(
            model_name='feedback',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
