# Generated by Django 3.2.23 on 2024-01-08 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20240108_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_on']},
        ),
    ]
