# Generated by Django 3.2.23 on 2024-01-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
